# Generated by Django 2.1.2 on 2018-10-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='current_nonce',
            field=models.BigIntegerField(default=0),
        ),
    ]
