# Generated by Django 2.1.2 on 2018-10-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20181020_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='signature',
            field=models.BinaryField(blank=True, max_length=1000000),
        ),
    ]
