# Generated by Django 2.1.2 on 2018-10-20 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20181020_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='timestamp',
        ),
    ]
