# Generated by Django 2.1.2 on 2018-10-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_remove_block_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='nonce',
            field=models.CharField(default='', max_length=100),
        ),
    ]
